[build]
  publish = "dist/"
  command = "npm run build"

[context.production.environment]
  NODE_ENV = "production"
  ENV_FILE = ".env.production"

[context.branch-deploy.environment]
  NODE_ENV = "development"
  ENV_FILE = ".env"
