create table
  public.matchs (
    id bigint generated by default as identity,
    created_at timestamp with time zone null default now(),
    league text not null,
    date timestamp with time zone null,
    venue text null,
    api_id bigint null,
    city text null,
    round text not null,
    status text null,
    team_a_goal smallint null,
    team_b_goal smallint null,
    season integer null,
    team_a bigint not null,
    team_b bigint not null,
    constraint matchs_pkey primary key (id),
    constraint matchs_apiId_key unique (api_id),
    constraint matchs_id_key unique (id),
    constraint matchs_team_a_fkey foreign key (team_a) references teams (id),
    constraint matchs_team_b_fkey foreign key (team_b) references teams (id)
  ) tablespace pg_default;

alter table "public"."matchs" enable row level security;
CREATE UNIQUE INDEX "matchs_apiId_key" ON public.matchs USING btree (api_id);
CREATE UNIQUE INDEX matchs_id_key ON public.matchs USING btree (id);
CREATE UNIQUE INDEX matchs_pkey ON public.matchs USING btree (id);
alter table "public"."matchs" add constraint "matchs_pkey" PRIMARY KEY using index "matchs_pkey";
alter table "public"."matchs" add constraint "matchs_apiId_key" UNIQUE using index "matchs_apiId_key";
alter table "public"."matchs" add constraint "matchs_id_key" UNIQUE using index "matchs_id_key";

CREATE POLICY "Enable read access for all users" ON "public"."matchs"
AS PERMISSIVE FOR SELECT
TO public
USING (true)

