create table "public"."matchs" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "league" character varying,
    "date" timestamp with time zone,
    "team_a" character varying,
    "team_b" character varying,
    "venue" character varying,
    "api_id" bigint,
    "city" character varying,
    "round" text null,
    "status" text null,
    "team_a_goal" smallint null,
    "team_b_goal" smallint null,
    "season" integer null
);


alter table "public"."matchs" enable row level security;
CREATE UNIQUE INDEX "matchs_apiId_key" ON public.matchs USING btree (api_id);
CREATE UNIQUE INDEX matchs_id_key ON public.matchs USING btree (id);
CREATE UNIQUE INDEX matchs_pkey ON public.matchs USING btree (id);
alter table "public"."matchs" add constraint "matchs_pkey" PRIMARY KEY using index "matchs_pkey";
alter table "public"."matchs" add constraint "matchs_apiId_key" UNIQUE using index "matchs_apiId_key";
alter table "public"."matchs" add constraint "matchs_id_key" UNIQUE using index "matchs_id_key";
