create table
  public.teams (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name character varying null,
    logo character varying null,
    constraint teams_pkey primary key (id)
  ) tablespace pg_default;

  
CREATE POLICY "Enable read access for all users" ON "public"."teams"
AS PERMISSIVE FOR SELECT
TO public
USING (true)
